myproject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('younger_user/<username>/', views.younger_user, name='younger_user'),
	path('elder_user/<username>/', views.elder_user, name='elder_user'),
	path('elder_profile/<username>/', views.elder_self_profile, name='elder_self_profile'),
	path('younger_profile/<username>/', views.younger_self_profile, name='younger_self_profile'),
    path('accounts/login/<type1>/', views.login_view, name='login'),
    path('accounts/register/<type1>/', views.register_view, name='register'),
    path('accounts/logout/', views.logout_view, name='logout'), 
    path('edit_profile_younger/<username>/', views.younger_edit_profile, name='younger_edit_profile'),
    path('edit_profile_elder/<username>/', views.elder_edit_profile, name='elder_edit_profile'),    
    path('number_of_oldies/<username>/<username1>/', views.number_of_oldies, name='number_of_oldies'),
    path('edit_current_status/<username>/',views.edit_current_status, name="edit_current_status"),
    path('remove/<username>/<username1>/', views.remove_user_from_current_status, name="remove_user_from_current_status"),
    path('add_elders/<username>/', views.add_elders_in_your_list, name="add_elders_in_your_list"),
    path('add_younger/<username>/', views.Add_younger_in_elder_table, name="Add_younger_in_elder_table"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myproject/myapp/models.py
from django.db import models

# Create your models here.

class Young_user(models.Model):
	Y_username = models.CharField(primary_key=True,max_length=20)
	name = models.CharField('Name', max_length=120)
	address = models.TextField(blank=True)
	gender = models.CharField(max_length=20)
	dob = models.DateField()
	social_profile = models.CharField('Social link', max_length=220)
	average_rating = models.IntegerField()
	experience = models.IntegerField()
	age = models.IntegerField()

	def __str__(self):
		return self.name


class elder_table(models.Model):
	younger_user = models.CharField(max_length=20)
	rating_by_elder = models.IntegerField()
	review_by_elder = models.CharField('Review', max_length=220)
	time_duration = models.IntegerField() 
	elder_user = models.CharField(max_length=20)

	def __str__(self):
		return self.elder_user

class younger_table(models.Model):
	elder_user = models.CharField(max_length=20)
	rating_by_younger = models.IntegerField()
	review_by_younger = models.CharField('Review', max_length=220)
	start_date = models.DateField(null=True)
	younger_user = models.CharField(max_length=20)

	def __str__(self):
		return self.elder_user



class ELDER_user(models.Model):
	E_username = models.CharField(primary_key=True,max_length=20)
	name1 = models.CharField('Name', max_length=120)
	address1 = models.TextField(blank=True)
	gender1 = models.CharField(max_length=20)
	dob1 = models.DateField()
	average_rating1 = models.IntegerField()

	def __str__(self):
		return self.name1


class Current_status_younger(models.Model):
	username = models.CharField(primary_key=True,max_length=20)
	elder_1 = models.CharField(max_length=20, blank=True)
	elder_2 = models.CharField(max_length=20, blank=True)
	elder_3 = models.CharField(max_length=20, blank=True)
	elder_4 = models.CharField(max_length=20, blank=True)
	elder_6 = models.CharField(max_length=20, blank=True)

	def __str__(self):
		return self.username

myproject/templates/add_elder.html
<!DOCTYPE html>
<html>
<head>
	  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
    .red{color: red;}
  </style>
</head>
<body>
	<div class="container"><br>
		<h2 class="text-center"><u>Add elder in your list!!</u></h2><br>
		<h2 class="text-center">{{username}}</h2><br><br>
	    <div class="container text-center">
  		<form method="post" class="form-inline">
  			{% csrf_token %}
  			{{form.as_p}}

        <label  for="id_younger_user">Younger user: </label>
          <input type="text" name="younger_user" maxlength="20" required id="id_younger_user" value="{{username}}"><br>
  			<br><button type="submit" class="btn btn-primary">Submit</button>
  		</form >
  	
  		</div>
  	</div>	
     <br><br>
  <div>
  <p class="text-center red"><b>{{error}}</b></p> 
  </div>
</body>
</html>

myproject/templates/add_younger.html
<!DOCTYPE html>
<html>
<head>
	  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
    .red{color: red;}
  </style>
</head>
<body>
	<div class="container"><br>
		<h2 class="text-center"><u>Add elder in your list!!</u></h2><br>
		<h2 class="text-center">{{username}}</h2><br><br>
	    <div class="container text-center">
  		<form method="post" class="form-inline">
  			{% csrf_token %}
  			{{form.as_p}}

        <label  for="id_younger_user">Elder user: </label>
          <input type="text" name="elder_user" maxlength="20" required id="id_elder_user" value="{{username}}"><br>
  			<br><button type="submit" class="btn btn-primary">Submit</button>
  		</form >
  	
  		</div>
  	</div>	
     <br><br>
  <div>
  <p class="text-center red"><b>{{error}}</b></p> 
  </div>
</body>
</html>

myproject/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
		{% block content %}
		{% endblock %}
		
</body>
</html>

myproject/templates/current_serving.html
<!DOCTYPE html>
<html>
<head>
	  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
    .red{color: red;}
  </style>
</head>
<body>
	<div class="container"><br>
		<h2 class="text-center"><u>Add elder in your list!!</u></h2><br>
		<h2 class="text-center">{{username}}</h2><br><br>
	    <div class="container text-center">
  		<form method="post" class="form-inline">
  			{% csrf_token %}
        <label  for="id_younger_user">Username: </label>
          <input type="text" name="elder_user" maxlength="20" required id="id_elder_user" value="{{username}}"><br><br>
  			{{form.as_p}}

  			<br><button type="submit" class="btn btn-primary">Submit</button>
  		</form >
  	
  		</div>
  	</div>	
     <br><br>
  <div>
  <p class="text-center red"><b>{{error}}</b></p> 
  </div>
</body>
</html>

myproject/templates/current_status.html
<!DOCTYPE html>
<html>
<head>
	  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
    .red{color:red;}
  </style>
</head>
<body>
<div class="container">
<div class="jumbotron text-center">
  <h1>Edit your current status!</h1>
  <p>{{username}}</p>
</div>
</div>


	<div class="container"><br>
  <div class="container text-center">

      <form class="form-inline" method="post" action="/edit_current_status/{{username}}/">
  		{% csrf_token %}
        <div class="form-group">
          <label  for="elder_1">Elder 1 - </label>
          <input type="text" class="form-control" id="elder_1" name="elder_1" value="{{status.elder_1}}">
        </div>
  <br><br>
        <div class="form-group">
          <label  for="elder_2">Elder 2 - </label>
          <input type="text" class="form-control" id="elder_2" name="elder_2" value="{{status.elder_2}}">
        </div>
  <br><br>
          <div class="form-group">
          <label  for="elder_3">Elder 3 - </label>
          <input type="text" class="form-control" id="elder_3" name="elder_3" value="{{status.elder_3}}">
        </div>
  <br><br>
          <div class="form-group">
          <label  for="elder_4">Elder 4 - </label>
          <input type="text" class="form-control" id="elder_4" name="elder_4" value="{{status.elder_4}}">
        </div>
  <br><br>


      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
	</div>
  <br>
  <div>
  <p class="text-center red"><b>{{error}}</b></p>	
  </div>
</body>
</html>

myproject/templates/edit_elder_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
  	#class1{  border-style: solid; border-width: medium;}
  	.ex1{max-height: 5px;}
    .blue{color:blue;}
  </style>
</head>
<body class="container">

<div class="jumbotron">
  <h2 class="text-center blue">Edit YOUR PROFILE</h2>
  <h3 class="text-center">{{user_name}}</h3>

</div>
<div class="container text-center" >
  <form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Save</button>
</form>

</div>
  


</body>
</html>

myproject/templates/edit_younger_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
  	#class1{  border-style: solid; border-width: medium;}
  	.ex1{max-height: 5px;}
    .blue{color:blue;}
  </style>
</head>
<body class="container">

<div class="jumbotron">
  <h2 class="text-center blue">Edit YOUR PROFILE</h2>
  <h3 class="text-center">{{user_name}}</h3>

</div>
<div class="container text-center" >
  <form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Save</button>
</form>

</div>
  


</body>
</html>

myproject/templates/elder_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>User_profile</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
  	#class1{  border-style: solid; border-width: medium;}
  	.ex1{max-height: 5px;}
    .review{height: 200px; width: 100%;border-style: solid; border-width: medium; padding: 2em;}
  </style>
</head>
<body class="container">

<div class="jumbotron">
	<div class="row">
	<div class="col-sm-4">
		<img src="{% static 'download.jpg' %}" class="img-rounded" id="class1" alt="Cinque Terre" width="200" height="236">
		<h5 class="text-center">Birth : {{user_data.dob1}}({{user_data.gender1}})</h5>
	</div>
	<div class="col-sm-8">
  		<h2>{{user_data.name1}}({{user_name}})</h2>
  		<h5>{{user_data.address}}</h5> <br>
  	
  		<h4>budget - 10k/mont</h4><br>
  		<h4>Currently serving by <a>Tiwari</a></h4>
	</div>
	</div>
</div>
  
<div class="container">
  <div class="row">
    <div class="col-sm-12">
    	<h3 class="text-center">Served By</h3>
      	<div style="overflow: auto; height: 210px">
   			<ul class="list-group">
    			<li class="list-group-item">Younger <span class="badge">review</span><span class="badge">time duration</span><span class="badge">rating</span></li>

          {% for data in younger_ %}
            <li class="list-group-item"><a href="/younger_user/{{data.younger_user}}/"> {{data.younger_user}} </a> <span class="badge" onclick="myFunction('{{data.review_by_elder}}')">review</span><span class="badge">{{data.time_duration}} months</span><span class="badge">7/10</span></li>
          {% endfor %}

  			</ul>
  		</div>
    </div>
 
  </div>
</div>
<div class="col-sm-12 text-center container">
  <div class="review container">
    <h5 class="text"></h5>
  </div>
</div><br><br>
<p class="text-center blue"><u><a href="/">Back to home</a></u></p>
<br><br><br>
</body>
</html>
<script>
function myFunction(data12)
{
  $(".text").text(data12);
}

</script>

myproject/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<style type="text/css">
  .class1{background-color: #dfebf2;}
  #abc{font-size: 30px;color: #5e5c5c;}
  #h1{color: #354f5e;}
  .class2{padding-left: 20px;}
</style>
<body class="container">

<div class="jumbotron text-center class1">
  <h1 id="h1">EDYOGA</h1>
  <p id="abc" >CareAll-Retired folks make <br>themselves available for care &<br> young can earn by taking care.</p> 
</div>
  
<div class="container" >
  <div class="row">
    <div class="col-sm-6" class="class2">
      <h3 class="text-center">ELDER</h3>
      <p class="text-center">SignUp for takecare of yourself</p>
      <p class="text-center"><a href="/accounts/register/elder/"><button type="button" class="btn btn-default">SignUp</button></a>&nbsp;<a href="/accounts/login/elder/"><button type="button" class="btn btn-default">Login</button></a></p>
    </div>
    <div class="col-sm-6">
      <h3 class="text-center">YOUNGER</h3>
      <p class="text-center">SignUp for making money by taking care of elders!</p>
      <p class="text-center"><a href="/accounts/register/younger/"><button type="button" class="btn btn-default">SignUp</button></a>&nbsp;<a href="/accounts/login/younger/"><button type="button" class="btn btn-default">Login</button></a></p>
    </div>
  
  </div>
</div>

</body>
</html>

myproject/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  	<style type="text/css">
  	  		h2{text-align: center;}
  		label{color:black;font-size: 20px;}
  		div{margin-left: 40%;}
  		li{color:white;}
  		button{margin-left:10%;}
  		body{
  			background: #e8e6e6;
  		}
      a:link{
        text-decoration: none;
        color:white;
      }
      #alink{
        text-align: right;  
        color:white;
        padding-right: 2em;
      }
      #a2{color: black;}
      .User_name{border-radius: 3px; font-weight: bold;}
.Password{border-radius: 3px; font-weight: bold;}	
  	</style>

</head>
<body><br>
<p id="alink"><a href="/" id="a2">Home</a></p>
<h2><u>Login</u></h2><br><br>
<div>

<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" class="btn btn-primary">Login</button>
</form>
</div>
</body>
</html>

myproject/templates/login_test.html
<html>
	<head>
		<title>login</title>
		<meta http-equiv="refresh" content="">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  		<style>
  			.c1{text-align: center;padding-top:10%;padding:5%;font-size: 40px;font-family:;color: white}
  			.c2{border: 2px;}
  			.c3{background-color: #897f8e;}
  			.c4{background-color: white;}
  			.c5{height:3%;}
  			.c6{width: 50%,}
        .c7{color:white;}
        .c8{text-align: right;color: white;padding-right: 20%;}
  		</style>
	</head>
	<body class="c3">
		<div class="container">

			<div class="form-group">
				<p class="c1">Login here </p>
			</div>
      <div class="form-group">
       <p class="c8"><a href="/" class="c7">Home</a></p>
      </div>
			<form class="form-horizontal" action="{{url_for('login')}}" method="POST">
  				<div class="input-group col-sm-offset-3 col-sm-6">
    				<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
    				<input id="email" type="text" class="form-control" name="email" placeholder="Email">
  				</div>
  				<div class="c5"></div>
  				<div class="input-group col-sm-offset-3 col-sm-6">
  			  		<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
    				<input id="password" type="password" class="form-control" name="password" placeholder="Password">
  				</div>
 				<div class="form-group"> 
 				   <div class="col-sm-offset-3 col-sm-10">
 					    <div class="c7 checkbox">
        					<label><input type="checkbox"> Remember me</label>
      					</div>
    				</div>
  				</div>
  				<div class="form-group"> 
  					<div class="col-sm-offset-3 col-sm-10">
    					<button type="submit" class="btn btn-default">Submit</button>
    				</div>
            <div class="form-group">
              <div class="c7 col-sm-offset-6 col-sm-10">
              <p>Have no account? <a href="/registration_page" class="c7"> click here!</a> </p>
              </div>             
            </div>
  				</div>
			</form>
      <div class="col-sm-offset-1 col-sm-10 c7">
      {% if error %}
        <p><strong>{{ error }}</strong></p>
      {% endif %}
      </div>
		</div>
	</body>	
</html>

myproject/templates/password_reset_confirm.html
{% extends "base_generic.html" %}

{% block content %}
    {% if validlink %}
        <p>Please enter (and confirm) your new password.</p>
        <form action="" method="post">
        {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">New password:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Confirm password:</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Change my password" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Password reset failed</h1>
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}
{% endblock %}

myproject/templates/password_reset_form.html
{% block content %}
  <form action="" method="post">
  {% csrf_token %}
  {% if form.email.errors %}
    {{ form.email.errors }}
  {% endif %}
      <p>{{ form.email }}</p> 
    <input type="submit" class="btn btn-default btn-lg" value="Reset password">
  </form>
{% endblock %}

myproject/templates/signup.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  	<style type="text/css">
  		  		h2{text-align: center;}
  		label{color:black;font-size: 20px;}
  		div{margin-left: 40%;}
  		li{color:black;}
  		button{margin-left:10%;}
  		body{
  			background: #e8e6e6
  		}
      a:link{
        text-decoration: none;
        color:black;
      }
      #alink{
        text-align: right;  
        color:black;
        padding-right: 2em;
      }
      #a2{color: black;}
.User_name, .email, .email2{border-radius: 3px; font-weight: bold;}
.Password{border-radius: 3px; font-weight: bold;}
.helptext{color: white;font-family: cursive;font-size: 10px;}
  	</style>

</head>
<body><br>
<p id="alink"><a href="/" id="a2">Home</a></p>
<h2><u>Registration</u></h2><br><br>
<div>

<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" class="btn btn-primary">Save</button>
</form>
</div>
</body>
</html>